/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzeria;
import modelo.PedidoProducto;
import control.PedidoProductoJpaController;
import control.PedidosJpaController;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Pedidos;
import modelo.Usuario;
/**
 *
 * @author noobe
 */
public class Carrito extends javax.swing.JFrame {
private Pedidos pedidoActual;
private Usuario usuarioActual;
private Icon imagen;
private boolean estado = false;
    /**
     * Creates new form Carrito
     */
    public Carrito(Usuario usuario, Pedidos pedido) {
        this.usuarioActual = usuario;
        this.pedidoActual = pedido;
        initComponents();
        enlistarProductos();
        
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Regresar al menú principal
                MenuPrincipal menu = new MenuPrincipal(usuarioActual, null, pedidoActual);
                menu.setVisible(true);
                dispose(); // Cierra sólo esta ventana
            }
        });
    }

   private BigDecimal calcularNuevoTotal() {
    BigDecimal total = BigDecimal.ZERO;
    for (int i = 0; i < contenidoP.getRowCount(); i++) {
        Object valor = contenidoP.getValueAt(i, 2);
        if (valor instanceof BigDecimal) {
            total = total.add((BigDecimal) valor);
        } else {
            total = total.add(new BigDecimal(valor.toString()));
        }
    }
    return total;
}
   
    private void enlistarProductos(){
        try {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("PizzeriaPU");
        PedidoProductoJpaController control = new PedidoProductoJpaController(emf);

        // Obtener todos los registros
        List<PedidoProducto> todos = control.findPedidoProductoEntities();

        // Filtrar solo los que pertenecen al pedido actual
        List<PedidoProducto> pedidos = new ArrayList<>();
        for (PedidoProducto pp : todos) {
            if (pp.getIdPedido().equals(pedidoActual)) {
                pedidos.add(pp);
            }
        }

        // Crear tabla
        DefaultTableModel tablita = new DefaultTableModel();
        tablita.addColumn("ID");
        tablita.addColumn("Nombre producto");
        tablita.addColumn("Cantidad");
        tablita.addColumn("Subtotal");

        for (PedidoProducto pp : pedidos) {
            tablita.addRow(new Object[]{
                pp.getIdPedidoProducto(),
                pp.getIdProducto().getNombre(),
                pp.getCantidad(),
                pp.getSubtotal()
            });
        }

        contenidoP.setModel(tablita);
        contenidoP.getColumnModel().getColumn(0).setMinWidth(0);
        contenidoP.getColumnModel().getColumn(0).setMaxWidth(0);

        } catch(Exception e){
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contenidoP = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Impact", 2, 18)); // NOI18N
        jLabel2.setText("Bienvenido a tu Carrito");

        contenidoP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(contenidoP);

        btnEliminar.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar Producto");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(0, 0, 0));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addGap(32, 32, 32)
                .addComponent(btnGuardar)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    int seleccion = contenidoP.getSelectedRow();
    
    
    if(seleccion != -1){
        try{
            
        
        int idPedidoProducto = (Integer) contenidoP.getValueAt(seleccion, 0);
        
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("PizzeriaPU");
        PedidoProductoJpaController seletsiones = new PedidoProductoJpaController(emf);
        seletsiones.destroy(idPedidoProducto);
        
        JOptionPane.showMessageDialog(this, "Producto Correctamente eliminado");
        enlistarProductos();
        
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error");
            e.printStackTrace();
        }
    } else {
        JOptionPane.showMessageDialog(this, "Selecciona un producto para eliminar");
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    try {
        BigDecimal nuevoTotal = calcularNuevoTotal();
        
        pedidoActual.setTotal(nuevoTotal); // Asume que tu entidad Pedidos tiene setTotal()
        
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("PizzeriaPU");
        PedidosJpaController controlador = new PedidosJpaController(emf);
        Pedidos actualizacion = controlador.findPedidos(pedidoActual.getIdPedido());
        
        actualizacion.setTotal(nuevoTotal);
        controlador.edit(actualizacion);
        
        JOptionPane.showMessageDialog(this, "Pedido actualizado con éxito.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al guardar los cambios del pedido.");
        e.printStackTrace();
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        MenuPrincipal atras = new MenuPrincipal(usuarioActual, imagen, pedidoActual);
        atras.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTable contenidoP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
