/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzeria;

import control.ProductoJpaController;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.math.BigDecimal;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.NoResultException;
import javax.persistence.Persistence;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Categoria;
import modelo.Ingrediente;
import modelo.Inventario;
import modelo.Producto;
import modelo.Usuario;
import modelo.Pedidos;

/**
 *
 * @author Talli
 */
public class Productos extends javax.swing.JFrame {
private Usuario usuarioActual;
private modelo.Pedidos pedidoActual;
    /**
     * Creates new form Ingredientes1
     */
    public Productos(Usuario usuario, Pedidos pedido) {
        initComponents();
        
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Regresar al menú principal
                MenuPrincipal menu = new MenuPrincipal(usuarioActual, null, pedidoActual);
                menu.setVisible(true);
                dispose(); // Cierra sólo esta ventana
            }
        });
        
        this.usuarioActual = usuario;
        this.pedidoActual = pedido;
        
        JComponent[] campos = {txtNomProducto, cbCategoria, txtIngredientes, txtCantidad, txtPrecio};

        for (int i = 0; i < campos.length; i++) {
            int indice = i; // necesario para el lambda
            campos[i].addKeyListener(new KeyAdapter() {
                @Override
                public void keyPressed(KeyEvent evt) {
                    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                        if (indice < campos.length - 1) {
                            campos[indice + 1].requestFocus(); // siguiente componente
                        } else {
                            btnAgregarActionPerformed(null);
                        }
                    }
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        txtNomProducto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIngredientes = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        cbCategoria = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel30.setFont(new java.awt.Font("Impact", 3, 36)); // NOI18N
        jLabel30.setText("Productos");

        txtNomProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomProductoActionPerformed(evt);
            }
        });
        txtNomProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomProductoKeyTyped(evt);
            }
        });

        jLabel1.setText("Nombre del producto");

        jLabel2.setText("Categoría");

        jLabel3.setText("Ingredientes");

        txtIngredientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIngredientesKeyTyped(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel4.setText("Precio");

        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });

        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pizzas", "Bebidas", "Postres", "Complementos" }));
        cbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriaActionPerformed(evt);
            }
        });

        jLabel5.setText("Cantidad");

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnRegresar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(cbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(txtNomProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(txtIngredientes)
                            .addComponent(txtPrecio)
                            .addComponent(txtCantidad))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel30)
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNomProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(btnAgregar))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomProductoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nombre = txtNomProducto.getText().trim();
    String categoriaSeleccionada = cbCategoria.getSelectedItem().toString();
    String ingredientesTexto = txtIngredientes.getText().trim();
    String precioTexto = txtPrecio.getText().trim();
    String cantidadTexto = txtCantidad.getText().trim();  // NUEVO CAMPO

    if (nombre.isEmpty() || ingredientesTexto.isEmpty() || precioTexto.isEmpty() || cantidadTexto.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, rellene todos los campos.");
        return;
    }

    BigDecimal precio;
    int cantidad;

    try {
        precio = new BigDecimal(precioTexto);
        if (precio.compareTo(BigDecimal.ZERO) <= 0) {
            JOptionPane.showMessageDialog(this, "El precio debe ser mayor que 0.");
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El precio no es válido.");
        return;
    }

    try {
        cantidad = Integer.parseInt(cantidadTexto);
        if (cantidad < 0) {
            JOptionPane.showMessageDialog(this, "La cantidad no puede ser negativa.");
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "La cantidad debe ser un número entero.");
        return;
    }

    // Procesar ingredientes ignorando espacios → Separación solo por comas
    String[] ingredientesArray = ingredientesTexto.replace(" ", "").split(",");

    EntityManagerFactory emf = Persistence.createEntityManagerFactory("PizzeriaPU");
    EntityManager em = emf.createEntityManager();

    try {
        List<Producto> repetido = em.createQuery(
                "SELECT p FROM Producto p WHERE LOWER(p.nombre) = :n", Producto.class)
                .setParameter("n", nombre.toLowerCase())
                .getResultList();

        if (!repetido.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ese producto ya existe.");
            em.close();
            emf.close();
            return;
        }
        em.getTransaction().begin();

        // 1. Crear producto
        Producto nuevo = new Producto();
        nuevo.setNombre(nombre);
        nuevo.setDescripcion(ingredientesTexto); // se guarda tal cual
        nuevo.setPrecio(precio);
        nuevo.setIdCategoria(new Categoria(cbCategoria.getSelectedIndex() + 1));

        em.persist(nuevo);
        em.flush(); // para obtener el id generado

        int idProductoGuardado = nuevo.getIdProducto();

        // 2. Registrar ingredientes en tabla ingredientes (solo si no existen)
        for (String ing : ingredientesArray) {
            if (ing.isEmpty()) continue;

            List<Ingrediente> existentes = em.createQuery(
                "SELECT i FROM Ingrediente i WHERE LOWER(i.nombre) = :n", Ingrediente.class
            ).setParameter("n", ing.toLowerCase())
             .getResultList();

            if (existentes.isEmpty()) {
                Ingrediente nuevoIng = new Ingrediente();
                nuevoIng.setNombre(ing);
                em.persist(nuevoIng);
            }
        }

        // 3. Agregar cantidad a tabla inventario
        Inventario inv = new Inventario();
        inv.setIdProducto(nuevo);       // RELACIÓN CON PRODUCTO
        inv.setCantidad(cantidad);      // CANTIDAD DEL NUEVO TEXTFIELD
        inv.setEstado(cantidad > 0 ? "Disponible" : "Agotado");

        em.persist(inv);

        em.getTransaction().commit();
        JOptionPane.showMessageDialog(this, "Producto registrado correctamente.");

        // Regresar al menú
        MenuPrincipal regreso = new MenuPrincipal(usuarioActual, null, pedidoActual);
        regreso.setVisible(true);
        this.dispose();

    } catch (Exception ex) {
        em.getTransaction().rollback();
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al registrar el producto.");
    } finally {
        em.close();
        emf.close();
    }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        MenuPrincipal atras = new MenuPrincipal(usuarioActual, null, pedidoActual);
        atras.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void cbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCategoriaActionPerformed

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        char c = evt.getKeyChar();
        String texto = txtPrecio.getText();

        // Permitir solo dígitos y un punto
        if (!Character.isDigit(c) && c != '.') {
            evt.consume();
            return;
        }

        // Evitar que el primer caracter sea un punto
        if (texto.isEmpty() && c == '.') {
            evt.consume();
            return;
        }

        // Evitar que escriban más de un punto decimal
        if (c == '.' && texto.contains(".")) {
            evt.consume();
            return;
        }

        // (Opcional) Limitar a dos decimales:
        if (texto.contains(".")) {
            int indexPunto = texto.indexOf(".");
            int decimales = texto.length() - indexPunto - 1;

            if (decimales >= 2) {  // Cambia a 3, 4, etc. si deseas más decimales
                evt.consume();
                return;
            }
        }

        // (Opcional) Limitar longitud total
        if (texto.length() >= 10) { // cambia a lo que necesites
            evt.consume();
        }

    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtNomProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomProductoKeyTyped
        char c = evt.getKeyChar();

        // Permite letras, números y espacio
        if (!Character.isLetterOrDigit(c) && c != KeyEvent.VK_SPACE) {
            evt.consume();  // Bloquea el carácter
        }

    }//GEN-LAST:event_txtNomProductoKeyTyped

    private void txtIngredientesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIngredientesKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isLetterOrDigit(c) 
        && c != KeyEvent.VK_SPACE
        && c != ',') {
            evt.consume();
        }
    }//GEN-LAST:event_txtIngredientesKeyTyped

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        char c = evt.getKeyChar();

        // Evita que se escriban letras
        if (!Character.isDigit(c)) {
            evt.consume();
            return;
        }

        // Evita más de 10 dígitos
        if (txtCantidad.getText().length() >= 3) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtIngredientes;
    private javax.swing.JTextField txtNomProducto;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
